import Head from 'next/head'
import { Inter } from 'next/font/google'
import { signIn, useSession } from "next-auth/react"
import Image from 'next/image'
import { useState } from 'react';

//Icons
import ArrowCircleRightIcon from '@mui/icons-material/ArrowCircleRight';
import ArrowCircleRightOutlinedIcon from '@mui/icons-material/ArrowCircleRightOutlined';
import { useRouter } from 'next/router';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter()
  const { data: session, status } = useSession()
  
  const [channelName, setChannelName] = useState('')

  function nameSubmit(e : React.SyntheticEvent){
    e.preventDefault() 
    router.push('/channel/'+channelName)
  }

  return (
    <>
      <Head>
        <title>Request Bot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className + 'h-auto'}>
        <div className={'flex justify-center items-center'}>
          {status === 'unauthenticated' && 
            <div id='signIn-card' className={'flex flex-col items-center'}>
              {/* <div>Sign In</div> */}
              <button className={`p-2 bg-[#9046ff] text-white flex justify-center items-center`} onClick={() => signIn('twitch')}>
                <Image alt="Twitch icon" src='/TwitchGlitchWhite.svg' height={20} width={20}></Image>
                <span className="pl-3">Sign in with Twitch</span>
              </button>
            </div>
          }
          {status === 'authenticated' && 
            <div id='welcome-card' className={'flex flex-col items-center'}>
              <h1 className={'text-4xl'}>Welcome, {session.user?.name}!</h1>
              <p className={'mt-2'}>{`You can view and request songs from a streamer's list by typing the channel name below:`}</p>
              <div className={'mt-4 flex items-center'}>
                <form id="nameForm" onSubmit={nameSubmit}><input className={'mr-4 text-black text-center'} type='text' value={channelName} onChange={(e) => setChannelName(e.target.value)}></input></form>
                <button disabled={!channelName} type="submit" form='nameForm'>
                  {channelName && 
                    <ArrowCircleRightIcon/>
                  }
                  {!channelName && 
                    <ArrowCircleRightOutlinedIcon/>
                  }
                </button>
              </div>
            </div>
          }
        </div>
      </main>
    </>
  )
}
