import type { Metadata } from "next";
import "./globals.css";
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';

export const metadata: Metadata = {
  title: "RequestBot",
  description: "Generated by create next app",
};

export default function RootLayout( {children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body className={`flex flex-col min-h-dvh bg-slate-800 text-white`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
