import type { Metadata } from "next";
import "./globals.css";
import Sidebar from './components/layout/Sidebar';
import Footer from './components/layout/Footer';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex flex-row min-h-dvh`}>
        <Sidebar />
        <div className={`flex flex-col w-full min-h-full bg-slate-300 dark:bg-slate-900 dark:text-white`}>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
